<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ERCollectionCheckerJP.Domain\ERCollectionCheckerJP.Domain.csproj" />
    <ProjectReference Include="..\ERCollectionCheckerJP.SaveParser\ERCollectionCheckerJP.SaveParser.csproj" />
    <ProjectReference Include="..\ERCollectionCheckerJP.ItemDatabase\ERCollectionCheckerJP.ItemDatabase.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
